### ISSUE TITLE
The toys export is missing items

### ISSUE THREAD

**Issue by SQLLord** [kevinclement/simplearmory-addon#3] opened 2021-04-27 14:19 UTC
I tried to export a list of toys and it is missing a bunch of toys for me.  I am missing this one in particular.  https://www.wowhead.com/item=182729/hearty-dragon-plume   also this one  https://www.wowhead.com/item=182694/stylish-black-parasol   for some reason the addon is missing grabbing these.

**Comment by seirl** [comment] 2021-04-28 09:19
Duplicate of #4

**Closed as completed by seirl** 2021-04-28 09:19 UTC
