### ISSUE TITLE
SimpleArmory addon only reporting Shadowlands toys

### ISSUE THREAD

**Issue by aaronincincy** [kevinclement/simplearmory-addon#5] opened 2022-06-25 14:15 UTC
I'm using version 0.9 of the SimpleArmory addon, and when I run `/sa toys` it only returns me the toys I have that were added in Shadowlands (things in the Shadowlands section, a few leatherworking toys, and my engineering wormhole)

**Comment by seirl** [comment] 2022-06-25 15:23
Duplicate of #4 

Fixed in f9008806c5a1353c7c9060c72801ac10a83d9e13, available as v0.10 on curseforge.

**Closed as completed by seirl** 2022-06-25 15:23 UTC
